/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2018-12-09 14:43:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addCourse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/F:/JavaWeb/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/StudentManager/WEB-INF/lib/taglibs-standard-impl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1384339662000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.1.jar", Long.valueOf(1541214165735L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>ZZU</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.default.css\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugins/jquery-1.7.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"js/plugins/jquery-ui-1.8.16.custom.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugins/jquery.cookie.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugins/jquery.uniform.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugins/jquery.validate.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugins/jquery.tagsinput.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugins/charCount.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugins/ui.spinner.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugins/chosen.jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/custom/general.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/custom/forms.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugins/colorpicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugins/jquery.jgrowl.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugins/jquery.alerts.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/custom/elements.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--[if IE 9]>\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"screen\" href=\"css/style.ie9.css\"/>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<!--[if IE 8]>\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"screen\" href=\"css/style.ie8.css\"/>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"withvernav\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"bodywrapper\">\r\n");
      out.write("\t\t<div class=\"topheader\">\r\n");
      out.write("\t\t\t<div class=\"left\">\r\n");
      out.write("\t\t\t\t<h1 class=\"logo\">\r\n");
      out.write("\t\t\t\t\tZZU<span>学生</span>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<span class=\"slogan\">信息管理系统</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--search-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<br clear=\"all\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--left-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t<!--<div class=\"notification\">\r\n");
      out.write("                <a class=\"count\" href=\"ajax/notifications.html\"><span>9</span></a>\r\n");
      out.write("        \t</div>-->\r\n");
      out.write("\t\t\t\t<div class=\"userinfo\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/StudentManager/images/thumbs/avatar.png\" alt=\"\" /> <span>");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--userinfo-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"userinfodrop\">\r\n");
      out.write("\t\t\t\t\t<div class=\"avatar\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"GetHeadShotServlet?No=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SESSION_NO }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"/StudentManager/images/thumbs/avatarbig.png\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"changetheme\">\r\n");
      out.write("\t\t\t\t\t\t\t切换主题: <br /> <a class=\"default\"></a> <a class=\"blueline\"></a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"greenline\"></a> <a class=\"contrast\"></a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"custombg\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--avatar-->\r\n");
      out.write("\t\t\t\t\t<div class=\"userdata\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/StudentManager/MyselfServlet?No=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SESSION_NO }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>开心每一天</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>健康每一天</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>奋斗每一天</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/StudentManager/password.jsp\">修改密码</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/StudentManager/LogoutServlet\">退出</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--userdata-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--userinfodrop-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--right-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--topheader-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t<ul class=\"headermenu\">\r\n");
      out.write("\t\t\t\t<li class=\"current\"><a href=\"teacher.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon icon-flatscreen\"></span>教师</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"headerwidget\">\r\n");
      out.write("\t\t\t\t<div class=\"earnings\">\r\n");
      out.write("\t\t\t\t\t<div class=\"one_half\">\r\n");
      out.write("\t\t\t\t\t\t<h4>每日一句</h4>\r\n");
      out.write("\t\t\t\t\t\t<h3>越努力,越幸运！</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- <!--one_half-->\r\n");
      out.write("\t\t\t\t\t<!--one_half last-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--earnings-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--headerwidget-->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--header-->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"vernav2 iconmenu\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a class=\"togglemenu\"></a> <br /> <br />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--leftmenu-->\r\n");
      out.write("\t\t<div class=\"centercontent\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"pageheader\">\r\n");
      out.write("\t\t\t\t<h1 class=\"pagetitle\">添加课程</h1>\r\n");
      out.write("\t\t\t\t<span class=\"pagedesc\">课程信息</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--pageheader-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"contentwrapper\" class=\"contentwrapper\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"validation\" class=\"subcontent\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<form id=\"form1\" class=\"stdform\" method=\"post\"\r\n");
      out.write("\t\t\t\t\t\taction=\"/StudentManager/AddCourseServlet\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<label>编号</label> <span class=\"field\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"course_no\" id=\"course_no\" class=\"longinput\" /></span>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<label>名称</label> <span class=\"field\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"course_name\" id=\"course_name\" class=\"longinput\" /></span>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<label>学分</label> <span class=\"field\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"credit\" id=\"\" credit\"\" class=\"longinput\" /></span>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<label>类型</label> <span class=\"field\"> <input id=\"type\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"type\" type=\"radio\" value=\"1\" />必修课 <input id=\"type\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"type\" type=\"radio\" value=\"2\" />选修课\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p class=\"stdformbutton\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"submit radius2\">提交</button>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--subcontent-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--contentwrapper-->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- centercontent -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--bodywrapper-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /addCourse.jsp(62,73) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${identity }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /addCourse.jsp(80,65) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SESSION_NO }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /addCourse.jsp(124,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${identity=='student' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<li><a href=\"#formsub\" class=\"editor\">学生信息</a> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"arrow\"></span>\r\n");
          out.write("\t\t\t\t\t\t<ul id=\"formsub\">\r\n");
          out.write("\t\t\t\t\t\t\t<li><a\r\n");
          out.write("\t\t\t\t\t\t\t\thref=\"/StudentManager/StudentBasicinfoServlet?page=first\">学生基本信息</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"/StudentManager/StudentScoreServlet\">学生成绩信息</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"/StudentManager/StudentCourseServlet\">课程信息</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a\r\n");
          out.write("\t\t\t\t\t\t\t\thref=\"/StudentManager/StudentChooseCourseServlet?page=first\">选课</a></li>\r\n");
          out.write("\t\t\t\t\t\t</ul></li>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /addCourse.jsp(136,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${identity=='teacher' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<li><a href=\"#error\" class=\"error\">教师信息</a> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"arrow\"></span>\r\n");
          out.write("\t\t\t\t\t\t<ul id=\"error\">\r\n");
          out.write("\t\t\t\t\t\t\t<li><a\r\n");
          out.write("\t\t\t\t\t\t\t\thref=\"/StudentManager/TeacherBasicinfoServlet?page=first\">教师基本信息</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"/StudentManager/TeacherCourseServlet\">任课信息</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"/StudentManager/TeacherStudentServlet\">学生基本信息</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a\r\n");
          out.write("\t\t\t\t\t\t\t\thref=\"/StudentManager/ShowStudentScoreServlet?page=first\">成绩信息</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"/StudentManager/addCourse.jsp\">添加课程</a></li>\r\n");
          out.write("\t\t\t\t\t\t</ul></li>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /addCourse.jsp(149,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${identity=='admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<li><a href=\"#formsub\" class=\"editor\">信息管理</a> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"arrow\"></span>\r\n");
          out.write("\t\t\t\t\t\t<ul id=\"formsub\">\r\n");
          out.write("\t\t\t\t\t\t\t<li><a\r\n");
          out.write("\t\t\t\t\t\t\t\thref=\"/StudentManager/StudentBasicinfoServlet?page=first\">学生基本信息</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"/StudentManager/register.jsp\">添加学生</a></li>\r\n");
          out.write("\t\t\t\t\t\t</ul></li>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t<li><a href=\"#error\" class=\"error\">教师管理</a> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"arrow\"></span>\r\n");
          out.write("\t\t\t\t\t\t<ul id=\"error\">\r\n");
          out.write("\t\t\t\t\t\t\t<li><a\r\n");
          out.write("\t\t\t\t\t\t\t\thref=\"/StudentManager/TeacherBasicinfoServlet?page=first\">教师基本信息</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a\r\n");
          out.write("\t\t\t\t\t\t\t\thref=\"/StudentManager/StudentChooseCourseServlet?page=first\">删除课程</a></li>\r\n");
          out.write("\t\t\t\t\t\t</ul></li>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
