/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2018-11-29 14:39:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.recruit;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.qst.itoffer.bean.Company;
import com.qst.itoffer.bean.Job;
import java.util.*;

public final class company_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.qst.itoffer.bean.Job");
    _jspx_imports_classes.add("com.qst.itoffer.bean.Company");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>企业信息展示</title>\r\n");
      out.write("<link href=\"css/base.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/company.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../top.jsp", out, false);
      out.write('\r');
      out.write('\n');

Company company = (Company)request.getAttribute("company");
List<Job> joblist = (List<Job>)request.getAttribute("joblist");

      out.write("\r\n");
      out.write("<div class=\"tn-grid\">\r\n");
      out.write("   <div class=\"bottomban\">\r\n");
      out.write("    <div class=\"bottombanbox\"> <img src=\"recruit/images/");
      out.print(company.getCompanyPic() );
      out.write("\" /> </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("<div class=\"tn-grid\">\r\n");
      out.write("  <div class=\"tn-widget-content\">\r\n");
      out.write("    <div class=\"tn-box-content\">\r\n");
      out.write("      <div class=\"tn-helper-clearfix\">\r\n");
      out.write("        <div class=\"it-main2\">\r\n");
      out.write("          <div class=\"it-ctn-heading\">\r\n");
      out.write("            <div class=\"it-title-line\"> <span> <em> ");
      out.print(company.getCompanyViewnum() );
      out.write(" </em> 浏览 </span>\r\n");
      out.write("              <h3> 企业简介 </h3>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"it-com-textnote\"> \r\n");
      out.write("          <span class=\"kuai\"> 所在地：");
      out.print(company.getCompanyArea() );
      out.write(" </span> \r\n");
      out.write("          <span class=\"kuai\"> 规模：");
      out.print(company.getCompanySize() );
      out.write(" </span> \r\n");
      out.write("          <span class=\"kuai\"> 性质：");
      out.print(company.getCompanyType() );
      out.write(" </span> </div>\r\n");
      out.write("          <div class=\"it-company-text\">\r\n");
      out.write("            <p class=\"p1\" style=\"padding-left: 30px;\">\r\n");
      out.write("            <span style=\"line-height: 1.5; font-size: 14px;\"> \r\n");
      out.write("           \t");
      out.print(company.getCompanyBrief() );
      out.write("\r\n");
      out.write("            </span> </p>\r\n");
      out.write("            <br />\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"it-content-seqbox\">\r\n");
      out.write("    <div id=\"morejob\"   >\r\n");
      out.write("      <div class=\"it-ctn-heading\">\r\n");
      out.write("        <div class=\"it-title-line\">\r\n");
      out.write("          <h3> 职位 </h3>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!--职位列表-->\r\n");
      out.write("      ");
 if(joblist!=null){
      		for(Job job:joblist){
      
      out.write("\r\n");
      out.write("      <div class=\"it-post-box tn-border-dashed\">\r\n");
      out.write("        <div class=\"it-post-name\">\r\n");
      out.write("          <div class=\"tn-helper-right it-post-btn\"> \r\n");
      out.write("          <a class=\"it-font-underline\" href=\"JobServlet?type=select&jobid=");
      out.print(job.getJobId());
      out.write("\">\r\n");
      out.write("          <span class=\"tn-icon-view\"></span><span class=tn-action-text>查看详细</span> </a>\r\n");
      out.write("          <a class=\"tn-button-small\" href=\"#\">\r\n");
      out.write("          <span class=\"tn-button-text\">申请</span> </a></div>\r\n");
      out.write("          <h3><a href=\"JobServlet?type=select&jobid=");
      out.print(job.getJobId());
      out.write('"');
      out.write('>');
      out.print(job.getJobName() );
      out.write("</a></h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"it-post\">\r\n");
      out.write("          <li style=\"width:300px;\">薪资： \r\n");
      out.write("          <span class=\"it-font-size\">");
      out.print(job.getJobSalary() );
      out.write("</span></li>\r\n");
      out.write("          <li style=\"width:250px;\"><span class=tn-text-note>工作地区：</span>\r\n");
      out.write("          <label for=\"\">");
      out.print(job.getJobArea() );
      out.write("</label>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li><span class=\"tn-text-note\">招聘人数：</span> ");
      out.print(job.getJobHiringnum() );
      out.write("</li>\r\n");
      out.write("          <li><span class=\"tn-text-note\">结束日期：</span> ");
      out.print(job.getJobEnddate() );
      out.write(" </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!--职位列表-->\r\n");
      out.write("      ");
	}
      	} 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<p class=\"it-back-to-top\" style=\" position:fixed\" id=\"backTop\" title=\"返回顶部\"> <a href=\"#top\"> <span> </span> 返回顶部 </a> </p>\r\n");
      out.write("\r\n");
      out.write("<!-- 网站公共尾部 -->\r\n");
      out.write("<iframe src=\"foot.html\" width=\"100%\" height=\"150\" scrolling=\"no\"\r\n");
      out.write("\t\tframeborder=\"0\"></iframe>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
