/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2018-12-06 08:27:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	// 获得请求的绝对地址
	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>注册 - 锐聘网</title>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("<link href=\"css/base.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/register.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<meta\r\n");
      out.write("\tcontent=\"大学生求职,大学生就业,大学生招聘,IT人才,IT人才招聘,大学生名企招聘,,大学生找工作,IT名企招聘，IT行业招聘，IT企业快速入职\"\r\n");
      out.write("\tname=\"keywords\">\r\n");
      out.write("<meta\r\n");
      out.write("\tcontent=\"锐聘专注于为企业提供高效的人力资源解决方案，同时面向IT类技术人才推出快速一站式免费就业服务。秉承QST青软实训人才服务理念，为数千家企业量身定做个性化、全程化的人才培养体系，同时帮助中高级人才铺设成功之路，为人才和企业架设起沟通之桥。\"\r\n");
      out.write("\tname=\"description\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar xhr = false;\r\n");
      out.write("\tfunction createXHR() {\r\n");
      out.write("\t\ttry {\r\n");
      out.write("\t\t\txhr = new XMLHttpRequest();\r\n");
      out.write("\t\t} catch (e) {\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t\txhr = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t} catch (e1) {\r\n");
      out.write("\t\t\t\txhr = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (!xhr)\r\n");
      out.write("\t\t\talert(\"初始化XMLHttpRequest对象失败！\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction ajaxValidate(emailObj){\r\n");
      out.write("\t\tcreateXHR();\r\n");
      out.write("\t\tvar url = \"ApplicantRegisterServlet\";\r\n");
      out.write("\t\tvar content = \"type=emailAjaxValidate&email=\" + emailObj.value;\r\n");
      out.write("\t\txhr.open(\"POST\", url, true);\r\n");
      out.write("\t\talert(\"open Servlet\");\r\n");
      out.write("\t\txhr.onreadystatechange = function() {\r\n");
      out.write("\t\t\tif (xhr.readyState == 4 && xhr.status == 200) {\r\n");
      out.write("\t\t\t\talert(xhr.responseText);\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"emailValidate\").innerHTML = xhr.responseText;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\talert(\"send\");\r\n");
      out.write("\t\txhr.setRequestHeader(\"Content-Length\",content.length);\r\n");
      out.write("\t\txhr.setRequestHeader(\"CONTENT-TYPE\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\txhr.send(content);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction validate() {\r\n");
      out.write("\t\tvar email = document.getElementById(\"email\");\r\n");
      out.write("\t\tvar password = document.getElementById(\"password\");\r\n");
      out.write("\t\tvar agree = document.getElementById(\"agree\");\r\n");
      out.write("\t\tvar pattern = /^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+(.[a-zA-Z0-9_-])+/;\r\n");
      out.write("\r\n");
      out.write("\t\tif (email.value == \"\") {\r\n");
      out.write("\t\t\talert(\"邮箱不能为空！\");\r\n");
      out.write("\t\t\temail.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (!pattern.test(email.value)) {\r\n");
      out.write("\t\t\talert(\"请输入正确的邮箱格式！\");\r\n");
      out.write("\t\t\temail.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (password.value == \"\") {\r\n");
      out.write("\t\t\talert(\"密码不能为空！\");\r\n");
      out.write("\t\t\tpassword.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (password.length<6 || password.length>12) {\r\n");
      out.write("\t\t\talert(\"密码长度不符合要求，请输入6-12位密码!\");\r\n");
      out.write("\t\t\tpassword.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (!agree.checked) {\r\n");
      out.write("\t\t\talert(\"请先同意本站服务条款！\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t//服务条款的显示跟隐藏\r\n");
      out.write("\tfunction showdiv() {\r\n");
      out.write("\t\tdocument.getElementById(\"bg\").style.display = \"block\";\r\n");
      out.write("\t\tdocument.getElementById(\"show\").style.display = \"block\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction hidediv() {\r\n");
      out.write("\t\tdocument.getElementById(\"bg\").style.display = \"none\";\r\n");
      out.write("\t\tdocument.getElementById(\"show\").style.display = \"none\";\r\n");
      out.write("\t}\r\n");
      out.write("\t//验证码的更换\r\n");
      out.write("\tfunction changeValidateCode() {\r\n");
      out.write("\t\tdocument.getElementById(\"validateCode\").src = \"ValidateCodeServlet?rand=\"\r\n");
      out.write("\t\t\t\t+ Math.random();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 网站公共头部 -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 注册部分开始 -->\r\n");
      out.write("\t<div class=\"content\">\r\n");
      out.write("\t\t<div class=\"page_name\">注册</div>\r\n");
      out.write("\t\t<div class=\"login_content\">\r\n");
      out.write("\t\t\t<form action=\"ApplicantRegisterServlet\" method=\"post\" onsubmit=\"return validate();\">\r\n");
      out.write("\t\t\t\t<div class=\"login_l\">\r\n");
      out.write("\t\t\t\t\t<div class=\"span1\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"tn-form-label\">邮箱：</label> \r\n");
      out.write("\t\t\t\t\t\t<input class=\"tn-textbox\" type=\"text\" name=\"email\" id=\"email\" onblur=\"ajaxValidate(this)\">\r\n");
      out.write("\t\t\t\t\t\t<label style=\"color: red\" id=\"emailValidate\"></label>\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"span1\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"tn-form-label\">密码：</label> <input class=\"tn-textbox\"\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"password\" name=\"password\" id=\"password\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"span1\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"tn-form-label\">验证码：</label> <input\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"tn-textbox-long\" type=\"text\" name=\"verifyCode\"> <span>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"ValidateCodeServlet\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"validateCode\" title=\"点击换一换\" onclick=\"changeValidateCode()\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:changeValidateCode();\">看不清？</a>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"tn-form-row-button\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"span1\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"submit\" type=\"submit\" class=\"tn-button-text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"立即注册\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"it-register-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"agree\" id=\"agree\" class=\"tn-checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tchecked=\"checked\" type=\"checkbox\"> <label>同意本站服务条款</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:showdiv();\">查看</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<div class=\"register_r\">\r\n");
      out.write("\t\t\t\t<p align=\"center\">\r\n");
      out.write("\t\t\t\t\t<br><br> <b>已有帐号？</b><a href=\"login.jsp\">登录</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<img height=\"230\" src=\"images/reg_pic.jpg\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 注册部分结束 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 服务条款部分开始 -->\r\n");
      out.write("\t<div id=\"bg\"></div>\r\n");
      out.write("\t<div id=\"show\">\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t服务条款<br />欢迎加入锐聘网。<br />所有用户，只要进入锐聘网注册，即被视为已经阅读、理解并同意本协议的以下各项条款。\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t\t免责条款：<br />第一条\r\n");
      out.write("\t\t用户在本站登记的简历信息，必须完整、正确。出于遵守国家相关法规的前提，我们有权在不经用户准许的情况下删除其在本站所登记的信息。<br />第二条\r\n");
      out.write("\t\t用户必须同意使用本站仅用于合法的目的。<br />第三条\r\n");
      out.write("\t\t本站如因系统维护或升级而需暂停服务时，将事先公告。若因线路及非本公司控制范围外的硬件故障或其它不可抗力而导致暂停服务，于暂停服务期间造成的一切不便与损失，本站不负任何责任。<br />第四条\r\n");
      out.write("\t\t本站使用者因为违反本声明的规定而触犯中华人民共和国法律的，一切后果自己负责，本站不承担任何责任。<br />第五条\r\n");
      out.write("\t\t凡以任何方式登录本站或直接、间接使用本站的资料者，视为自愿接受本站声明的约束。本声明未涉及的问题参见国家有关法律法规，当本声明与国家法律法规冲突时，以国家法律法规为准。\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t<input type=\"button\" onclick=\"javascript:hidediv()\"\r\n");
      out.write("\t\t\t\tclass=\"tn-button-text\" value=\"我明白了\">\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 服务条款部分结束 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 网站公共尾部 -->\r\n");
      out.write("\t<iframe src=\"foot.html\" width=\"100%\" height=\"150\" scrolling=\"no\"\r\n");
      out.write("\t\tframeborder=\"0\"></iframe>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
